# Generated by Django 4.2.7 on 2024-01-30 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('gameboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='game_assigned',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories_avail', to='gameboard_app.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gameboards', to='user_app.user'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='category_assigned',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_list', to='gameboard_app.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='question_files/'),
        ),
        migrations.AddField(
            model_name='question',
            name='pic',
            field=models.ImageField(blank=True, default='', upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='played',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=100),
        ),
    ]
