# Generated by Django 4.2.7 on 2023-12-29 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='game_assigned',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories_avail', to='gameboard_app.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='category_assigned',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_list', to='gameboard_app.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=100),
        ),
    ]
