# Generated by Django 4.2.7 on 2024-01-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameboard_app', '0002_category_game_assigned_question_category_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
