# Generated by Django 4.2.7 on 2024-01-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameboard_app', '0003_game_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
