# Generated by Django 4.2.7 on 2024-01-16 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('gameboard_app', '0004_rename_isactive_game_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gameboards', to='user_app.user'),
            preserve_default=False,
        ),
    ]
