# Generated by Django 4.2.7 on 2024-01-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameboard_app', '0005_game_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
