# Generated by Django 4.2.7 on 2024-01-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameboard_app', '0006_question_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='pic',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
