# Generated by Django 4.2.7 on 2024-01-30 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameboard_app', '0007_question_file_question_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='file',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pic',
        ),
    ]
